version: "3.8"

services:
  # postgres-recipe:
  #   image: postgres:latest
  #   container_name: postgres-recipe
  #   ports:
  #     - protocol: tcp
  #       published: 5433
  #       target: 5432
  #   environment:
  #     POSTGRES_PASSWORD: user_service
  #     POSTGRES_DB: user_service
  # content-service:
  #   image: postgres:latest
  #   container_name: content-service
  #   ports:
  #     - protocol: tcp
  #       published: 5434
  #       target: 5432
  #   environment:
  #     POSTGRES_PASSWORD: content_service
  #     POSTGRES_DB: content_service
  kong-database:
    image: postgres:latest
    ports:
      - protocol: tcp
        published: 5435
        target: 5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - ./data:/var/lib/postgresql/data
    # networks:
    #   - kong-network
  kong-migration:
    image: kong:latest
    # command: kong migrations bootstrap
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PG_PORT=5432
    depends_on:
      - kong-database
    # networks:
    #   - kong-network
  kong:
    image: kong:latest
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - kong-database
      - kong-migration
    # command: kong migrations up
    # networks:
    #   - kong-network
      
  konga:
    image: pantsel/konga
    ports:
      - 1337:1337
    links:
      - kong:kong
    container_name: konga
    environment:
      - NODE_ENV=production

networks:
  default:
      name: kong-network
      external: true
