version: "3.8"

services:
  postgres-recipe:
    image: postgres:latest
    container_name: postgres-recipe
    ports:
      - protocol: tcp
        published: 5433
        target: 5432
    environment:
      POSTGRES_PASSWORD: user_service
      POSTGRES_DB: user_service
  content-service:
    image: postgres:latest
    container_name: content-service
    ports:
      - protocol: tcp
        published: 5434
        target: 5432
    environment:
      POSTGRES_PASSWORD: content_service
      POSTGRES_DB: content_service
