version: "3.5"

services:
  postgre:
    container_name: postgresql
    image: postgres:14.7
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.16
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning 
    environment:
      REDIS_PASSWORD: redislocal
    volumes: 
      - redis_data:/var/lib/redis/data

  mongo:
    container_name: mongodb
    image: mongo:5.0.16
    ports:
      - 27017:27017   
    volumes: 
      - mongo_data:/var/lib/mongo/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

volumes:
  postgres_data:
  redis_data:
  mongo_data: